import type { ResultsPageData } from "@/lib/types";

export interface FeaturedSearch {
  slug: string;
  query: string;
  data: Omit<ResultsPageData, "queryId">;
}

export const featuredSearches: FeaturedSearch[] = [
  {
    slug: "headphones-good-for-sleeping",
    query: "headphones that are good for sleeping",
    data: {
      rawQuery: "headphones that are good for sleeping",
      parsedIntent: {
        useCase: "sleeping",
        constraints: ["comfortable for side sleeping", "low profile"],
        mustHaves: ["thin design", "comfortable padding"],
        niceToHaves: ["wireless", "noise masking"],
      },
      candidateCount: 87,
      methodology: "We analyzed 87+ sleep headphones by gathering real user opinions from Reddit, TikTok, Trustpilot, and review sites. Products were scored on comfort for side sleeping, sound quality, battery life, and overall user satisfaction.",
      buyingAdvice: "When shopping for sleep headphones, prioritize comfort and a thin profile — especially if you're a side sleeper. Wireless options offer convenience but check battery life lasts through the night. Our top picks balance real-world user satisfaction with sleep-specific design.",
      top10: [
        {
          rank: 1,
          product: { brand: "Bose", model: "Sleepbuds II", slug: "bose-sleepbuds-ii", category: "Sleep Headphones" },
          summary: "Purpose-built for sleep with a tiny form factor and curated soundscapes. Overwhelmingly recommended by side sleepers on Reddit.",
          tagline: "Purpose-built for sleep with a tiny form factor and curated soundscapes.",
          rankLabel: "Our Pick",
          pros: ["Side sleeper friendly", "Ultra compact", "Noise masking"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["side sleeper friendly", "ultra compact", "noise masking"],
          redditEvidence: [
            { quote: "These are the only buds I can sleep in without any pressure on my ears.", url: "https://reddit.com/r/headphones/example1" },
            { quote: "Sleepbuds II changed my sleep quality dramatically. Worth every penny.", url: "https://reddit.com/r/sleep/example1" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "medium", Trustpilot: "medium", Web: "high" },
          sourceCount: 42,
          scores: { queryFit: 95, redditEndorsement: 88, socialProofCoverage: 82, riskScore: 12, confidenceScore: 90, overall: 91 },
          sources: [],
        },
        {
          rank: 2,
          product: { brand: "CozyPhones", model: "Sleep Headphones Headband", slug: "cozyphones-sleep-headband", category: "Sleep Headphones" },
          summary: "Budget-friendly headband design with flat speakers. Hugely popular for the comfort-to-price ratio.",
          tagline: "Budget-friendly headband design with flat speakers.",
          rankLabel: "Runner-Up",
          pros: ["Headband design", "Budget friendly", "Washable"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["headband design", "budget friendly", "washable"],
          redditEvidence: [
            { quote: "Best $20 I ever spent. I fall asleep to podcasts every night now.", url: "https://reddit.com/r/BudgetAudiophile/example2" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "low", Trustpilot: "low", Web: "medium" },
          sourceCount: 31,
          scores: { queryFit: 90, redditEndorsement: 85, socialProofCoverage: 68, riskScore: 15, confidenceScore: 82, overall: 85 },
          sources: [],
        },
        {
          rank: 3,
          product: { brand: "Amazfit", model: "ZenBuds", slug: "amazfit-zenbuds", category: "Sleep Headphones" },
          summary: "Tiny earbuds with sleep monitoring and soothing sounds. Great for data-driven sleepers.",
          tagline: "Tiny earbuds with sleep monitoring and soothing sounds.",
          rankLabel: "Also Great",
          pros: ["Sleep tracking", "Compact", "Soothing sounds"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["sleep tracking", "compact", "soothing sounds"],
          redditEvidence: [
            { quote: "The sleep tracking integration is a nice bonus on top of solid sound blocking.", url: "https://reddit.com/r/gadgets/example3" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "low", Trustpilot: "low", Web: "medium" },
          sourceCount: 18,
          scores: { queryFit: 82, redditEndorsement: 65, socialProofCoverage: 55, riskScore: 20, confidenceScore: 68, overall: 72 },
          sources: [],
        },
        {
          rank: 4,
          product: { brand: "Soundcore", model: "Sleep A20", slug: "soundcore-sleep-a20", category: "Sleep Headphones" },
          summary: "Anker's entry into sleep earbuds with excellent passive noise blocking and a slim wing-tip design.",
          tagline: "Anker's entry into sleep earbuds with excellent passive noise blocking and a slim wing-tip design.",
          rankLabel: undefined,
          pros: ["Noise blocking", "Slim profile", "Long battery"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["noise blocking", "slim profile", "long battery"],
          redditEvidence: [
            { quote: "Battery lasts all night and they don't fall out. Better than Bose at half the price.", url: "https://reddit.com/r/headphones/example4" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "medium", Trustpilot: "low", Web: "high" },
          sourceCount: 35,
          scores: { queryFit: 88, redditEndorsement: 80, socialProofCoverage: 72, riskScore: 10, confidenceScore: 85, overall: 84 },
          sources: [],
        },
        {
          rank: 5,
          product: { brand: "Shokz", model: "OpenRun Mini", slug: "shokz-openrun-mini", category: "Bone Conduction" },
          summary: "Bone conduction leaves ears open — some sleepers prefer this for awareness. Mixed opinions for pillow use.",
          tagline: "Bone conduction leaves ears open — some sleepers prefer this for awareness.",
          rankLabel: undefined,
          pros: ["Bone conduction", "Open ear", "Lightweight"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["bone conduction", "open ear", "lightweight"],
          redditEvidence: [
            { quote: "I use these for back sleeping. Can still hear my alarm which is important for me.", url: "https://reddit.com/r/sleep/example5" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "medium", Trustpilot: "medium", Web: "high" },
          sourceCount: 22,
          scores: { queryFit: 65, redditEndorsement: 60, socialProofCoverage: 70, riskScore: 25, confidenceScore: 62, overall: 65 },
          sources: [],
        },
        {
          rank: 6,
          product: { brand: "Perytong", model: "Sleep Headphones Bluetooth Headband", slug: "perytong-sleep-headband", category: "Sleep Headphones" },
          summary: "Ultra-affordable headband option with Bluetooth 5.2. A top Amazon seller in the sleep headphone category.",
          tagline: "Ultra-affordable headband option with Bluetooth 5.2.",
          rankLabel: undefined,
          pros: ["Ultra budget", "Headband", "Bluetooth 5.2"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["ultra budget", "headband", "bluetooth 5.2"],
          redditEvidence: [
            { quote: "For under $15 these are shockingly good. Sound quality is fine for white noise and podcasts.", url: "https://reddit.com/r/BudgetAudiophile/example6" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "low", Trustpilot: "none", Web: "medium" },
          sourceCount: 15,
          scores: { queryFit: 80, redditEndorsement: 62, socialProofCoverage: 45, riskScore: 30, confidenceScore: 55, overall: 62 },
          sources: [],
        },
        {
          rank: 7,
          product: { brand: "QuietOn", model: "3.1", slug: "quieton-3-1", category: "Sleep Earbuds" },
          summary: "Active noise cancelling earbuds designed specifically for sleep. Premium option with strong ANC performance.",
          tagline: "Active noise cancelling earbuds designed specifically for sleep.",
          rankLabel: undefined,
          pros: ["Active noise cancelling", "Premium", "Snoring blocker"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["active noise cancelling", "premium", "snoring blocker"],
          redditEvidence: [
            { quote: "These block my partner's snoring completely. Game changer for light sleepers.", url: "https://reddit.com/r/sleep/example7" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "low", Trustpilot: "medium", Web: "medium" },
          sourceCount: 19,
          scores: { queryFit: 85, redditEndorsement: 68, socialProofCoverage: 60, riskScore: 18, confidenceScore: 65, overall: 70 },
          sources: [],
        },
        {
          rank: 8,
          product: { brand: "Sony", model: "WF-1000XM5", slug: "sony-wf-1000xm5", category: "True Wireless" },
          summary: "Not designed for sleep but some users swear by the ANC. Compact enough for some back sleepers.",
          tagline: "Not designed for sleep but some users swear by the ANC.",
          rankLabel: undefined,
          pros: ["Class-leading ANC", "Premium sound", "Compact"],
          cons: ["Limited social proof available", "May not suit all use cases"],
          fitCriteria: ["class-leading ANC", "premium sound", "compact"],
          redditEvidence: [
            { quote: "I know they're not sleep buds but the ANC is so good I accidentally fall asleep with them.", url: "https://reddit.com/r/SonyHeadphones/example8" },
          ],
          confidenceLevel: "low",
          platformCoverage: { Reddit: "high", TikTok: "high", Trustpilot: "medium", Web: "high" },
          sourceCount: 28,
          scores: { queryFit: 50, redditEndorsement: 75, socialProofCoverage: 90, riskScore: 35, confidenceScore: 48, overall: 55 },
          sources: [],
        },
        {
          rank: 9,
          product: { brand: "Maxrock", model: "Sleep Earbuds", slug: "maxrock-sleep-earbuds", category: "Sleep Earbuds" },
          summary: "Wired, ultra-slim silicone earbuds for minimalists who don't want to charge another device.",
          tagline: "Wired, ultra-slim silicone earbuds for minimalists who don't want to charge another device.",
          rankLabel: undefined,
          pros: ["Wired", "Ultra slim", "No charging needed"],
          cons: ["Limited social proof available", "May not suit all use cases"],
          fitCriteria: ["wired", "ultra slim", "no charging needed"],
          redditEvidence: [
            { quote: "Dead simple. Plug in, put on white noise, sleep. No batteries to worry about.", url: "https://reddit.com/r/headphones/example9" },
          ],
          confidenceLevel: "low",
          platformCoverage: { Reddit: "medium", TikTok: "none", Trustpilot: "none", Web: "low" },
          sourceCount: 11,
          scores: { queryFit: 75, redditEndorsement: 55, socialProofCoverage: 30, riskScore: 28, confidenceScore: 42, overall: 50 },
          sources: [],
        },
        {
          rank: 10,
          product: { brand: "Kokoon", model: "Nightbuds", slug: "kokoon-nightbuds", category: "Sleep Earbuds" },
          summary: "Slim profile with a companion sleep app and auto-fade audio. Aimed squarely at the sleep market.",
          tagline: "Slim profile with a companion sleep app and auto-fade audio.",
          rankLabel: undefined,
          pros: ["Sleep app integration", "Auto-fade", "Slim design"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["sleep app integration", "auto-fade", "slim design"],
          redditEvidence: [
            { quote: "The auto-fade feature is brilliant. Audio fades out once the app detects you've fallen asleep.", url: "https://reddit.com/r/sleep/example10" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "low", TikTok: "low", Trustpilot: "medium", Web: "medium" },
          sourceCount: 14,
          scores: { queryFit: 82, redditEndorsement: 50, socialProofCoverage: 52, riskScore: 22, confidenceScore: 55, overall: 60 },
          sources: [],
        },
      ],
    },
  },
  {
    slug: "best-standing-desk-under-500",
    query: "best standing desk under $500",
    data: {
      rawQuery: "best standing desk under $500",
      parsedIntent: {
        useCase: "standing desk for home office",
        constraints: ["under $500"],
        mustHaves: ["height adjustable", "sturdy build"],
        niceToHaves: ["programmable presets", "cable management"],
      },
      candidateCount: 112,
      methodology: "We analyzed 112+ standing desks by gathering real user opinions from Reddit, TikTok, Trustpilot, and review sites. Products were scored on stability, motor quality, price-to-value ratio, and long-term durability.",
      buyingAdvice: "When shopping for a standing desk under $500, prioritize stability at max height and motor reliability. Dual-motor systems tend to be smoother and more durable. Our top picks balance real-world user satisfaction with build quality.",
      top10: [
        {
          rank: 1,
          product: { brand: "Uplift", model: "V2 Standing Desk", slug: "uplift-v2", category: "Standing Desk" },
          summary: "Consistently top-rated across Reddit and review sites. Rock-solid stability and extensive customization options.",
          tagline: "Consistently top-rated across Reddit and review sites.",
          rankLabel: "Our Pick",
          pros: ["Stable at height", "Programmable presets", "7-year warranty"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["stable at height", "programmable presets", "7-year warranty"],
          redditEvidence: [
            { quote: "I've had the Uplift V2 for 2 years now and it's as solid as day one. Zero wobble.", url: "https://reddit.com/r/StandingDesk/example1" },
            { quote: "Best desk in the sub-$500 range and it's not even close.", url: "https://reddit.com/r/homeoffice/example1" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "medium", Trustpilot: "medium", Web: "high" },
          sourceCount: 48,
          scores: { queryFit: 95, redditEndorsement: 92, socialProofCoverage: 85, riskScore: 8, confidenceScore: 93, overall: 93 },
          sources: [],
        },
        {
          rank: 2,
          product: { brand: "FlexiSpot", model: "E7 Pro", slug: "flexispot-e7-pro", category: "Standing Desk" },
          summary: "Excellent value with a dual-motor system and solid weight capacity. Very popular on Reddit for the price.",
          tagline: "Excellent value with a dual-motor system and solid weight capacity.",
          rankLabel: "Runner-Up",
          pros: ["Dual motor", "High weight capacity", "Great value"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["dual motor", "high weight capacity", "great value"],
          redditEvidence: [
            { quote: "FlexiSpot E7 is the best bang for your buck. Dual motors and no wobble under $400.", url: "https://reddit.com/r/StandingDesk/example2" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "medium", Trustpilot: "medium", Web: "high" },
          sourceCount: 39,
          scores: { queryFit: 93, redditEndorsement: 88, socialProofCoverage: 78, riskScore: 10, confidenceScore: 88, overall: 90 },
          sources: [],
        },
        {
          rank: 3,
          product: { brand: "Fully", model: "Jarvis Bamboo", slug: "fully-jarvis-bamboo", category: "Standing Desk" },
          summary: "Eco-friendly bamboo top with a smooth lifting mechanism. A long-time favorite in the WFH community.",
          tagline: "Eco-friendly bamboo top with a smooth lifting mechanism.",
          rankLabel: "Also Great",
          pros: ["Bamboo top", "Smooth motor", "Eco-friendly"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["bamboo top", "smooth motor", "eco-friendly"],
          redditEvidence: [
            { quote: "The Jarvis has been my daily driver for 3 years. Bamboo top still looks great.", url: "https://reddit.com/r/homeoffice/example3" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "low", Trustpilot: "medium", Web: "high" },
          sourceCount: 36,
          scores: { queryFit: 88, redditEndorsement: 82, socialProofCoverage: 75, riskScore: 12, confidenceScore: 85, overall: 85 },
          sources: [],
        },
        {
          rank: 4,
          product: { brand: "Vari", model: "Electric Standing Desk", slug: "vari-electric", category: "Standing Desk" },
          summary: "Simple out-of-box experience with T-style legs and solid stability. Great for minimal setup.",
          tagline: "Simple out-of-box experience with T-style legs and solid stability.",
          rankLabel: undefined,
          pros: ["Easy assembly", "T-style legs", "Programmable"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["easy assembly", "T-style legs", "programmable"],
          redditEvidence: [
            { quote: "Setup took 15 minutes. It just works. Exactly what I wanted.", url: "https://reddit.com/r/StandingDesk/example4" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "low", Trustpilot: "medium", Web: "high" },
          sourceCount: 25,
          scores: { queryFit: 82, redditEndorsement: 70, socialProofCoverage: 72, riskScore: 15, confidenceScore: 75, overall: 76 },
          sources: [],
        },
        {
          rank: 5,
          product: { brand: "Branch", model: "Standing Desk", slug: "branch-standing-desk", category: "Standing Desk" },
          summary: "Minimalist design with a focus on stability. Gained a loyal following from the DTC office furniture space.",
          tagline: "Minimalist design with a focus on stability.",
          rankLabel: undefined,
          pros: ["Minimalist", "Quiet motor", "Clean cable management"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["minimalist", "quiet motor", "clean cable management"],
          redditEvidence: [
            { quote: "Branch is underrated. Super quiet motor and the desk looks way more expensive than it is.", url: "https://reddit.com/r/homeoffice/example5" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "low", Trustpilot: "low", Web: "medium" },
          sourceCount: 18,
          scores: { queryFit: 80, redditEndorsement: 65, socialProofCoverage: 55, riskScore: 18, confidenceScore: 68, overall: 70 },
          sources: [],
        },
        {
          rank: 6,
          product: { brand: "IKEA", model: "BEKANT", slug: "ikea-bekant", category: "Standing Desk" },
          summary: "Affordable IKEA option that's easy to find. Decent for light use but some report wobble at max height.",
          tagline: "Affordable IKEA option that's easy to find.",
          rankLabel: undefined,
          pros: ["Widely available", "Affordable", "IKEA ecosystem"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["widely available", "affordable", "IKEA ecosystem"],
          redditEvidence: [
            { quote: "It's IKEA — easy to get, easy to assemble, does the job for light desk setups.", url: "https://reddit.com/r/IKEA/example6" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "medium", Trustpilot: "low", Web: "high" },
          sourceCount: 22,
          scores: { queryFit: 75, redditEndorsement: 58, socialProofCoverage: 68, riskScore: 25, confidenceScore: 60, overall: 63 },
          sources: [],
        },
        {
          rank: 7,
          product: { brand: "Autonomous", model: "SmartDesk Pro", slug: "autonomous-smartdesk-pro", category: "Standing Desk" },
          summary: "Aggressive pricing with solid specs on paper. Mixed reviews on long-term reliability.",
          tagline: "Aggressive pricing with solid specs on paper.",
          rankLabel: undefined,
          pros: ["Budget friendly", "Dual motor", "Wide range"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["budget friendly", "dual motor", "wide range"],
          redditEvidence: [
            { quote: "Good desk for the price but customer service is hit or miss if something goes wrong.", url: "https://reddit.com/r/StandingDesk/example7" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "medium", Trustpilot: "low", Web: "medium" },
          sourceCount: 20,
          scores: { queryFit: 78, redditEndorsement: 55, socialProofCoverage: 62, riskScore: 30, confidenceScore: 55, overall: 60 },
          sources: [],
        },
        {
          rank: 8,
          product: { brand: "Fezibo", model: "Electric Standing Desk", slug: "fezibo-electric", category: "Standing Desk" },
          summary: "Amazon best-seller at a low price point. Great entry-level option with surprising features for the price.",
          tagline: "Amazon best-seller at a low price point.",
          rankLabel: undefined,
          pros: ["Amazon best seller", "Under $300", "Drawer included"],
          cons: ["Limited social proof available", "May not suit all use cases"],
          fitCriteria: ["Amazon best seller", "under $300", "drawer included"],
          redditEvidence: [
            { quote: "For $250 with a drawer? Can't beat it for a first standing desk.", url: "https://reddit.com/r/BudgetAudiophile/example8" },
          ],
          confidenceLevel: "low",
          platformCoverage: { Reddit: "low", TikTok: "medium", Trustpilot: "none", Web: "medium" },
          sourceCount: 14,
          scores: { queryFit: 72, redditEndorsement: 48, socialProofCoverage: 50, riskScore: 32, confidenceScore: 45, overall: 52 },
          sources: [],
        },
        {
          rank: 9,
          product: { brand: "ApexDesk", model: "Elite Series 60\"", slug: "apexdesk-elite-60", category: "Standing Desk" },
          summary: "Large desktop and smooth operation. Good for users who need a lot of surface area on a budget.",
          tagline: "Large desktop and smooth operation.",
          rankLabel: undefined,
          pros: ["60 inch top", "Smooth lift", "Spacious"],
          cons: ["Limited social proof available", "May not suit all use cases"],
          fitCriteria: ["60 inch top", "smooth lift", "spacious"],
          redditEvidence: [
            { quote: "If you need a big desk surface under $500, ApexDesk is hard to beat.", url: "https://reddit.com/r/StandingDesk/example9" },
          ],
          confidenceLevel: "low",
          platformCoverage: { Reddit: "low", TikTok: "none", Trustpilot: "low", Web: "medium" },
          sourceCount: 12,
          scores: { queryFit: 70, redditEndorsement: 45, socialProofCoverage: 42, riskScore: 28, confidenceScore: 42, overall: 48 },
          sources: [],
        },
        {
          rank: 10,
          product: { brand: "SHW", model: "Electric Height Adjustable Desk", slug: "shw-electric", category: "Standing Desk" },
          summary: "The budget king. Under $200 and gets the job done for basic sit/stand needs.",
          tagline: "The budget king.",
          rankLabel: undefined,
          pros: ["Ultra budget", "Single motor", "Compact options"],
          cons: ["Limited social proof available", "May not suit all use cases"],
          fitCriteria: ["ultra budget", "single motor", "compact options"],
          redditEvidence: [
            { quote: "You're not going to find a cheaper standing desk that actually works. It's basic but functional.", url: "https://reddit.com/r/homeoffice/example10" },
          ],
          confidenceLevel: "low",
          platformCoverage: { Reddit: "low", TikTok: "none", Trustpilot: "none", Web: "low" },
          sourceCount: 9,
          scores: { queryFit: 65, redditEndorsement: 40, socialProofCoverage: 30, riskScore: 35, confidenceScore: 38, overall: 42 },
          sources: [],
        },
      ],
    },
  },
  {
    slug: "mechanical-keyboard-for-programming",
    query: "mechanical keyboard for programming",
    data: {
      rawQuery: "mechanical keyboard for programming",
      parsedIntent: {
        useCase: "programming and typing",
        constraints: ["mechanical switches"],
        mustHaves: ["good typing feel", "reliable build"],
        niceToHaves: ["hot-swappable", "programmable keys", "quiet switches"],
      },
      candidateCount: 134,
      methodology: "We analyzed 134+ mechanical keyboards by gathering real user opinions from Reddit, TikTok, Trustpilot, and review sites. Products were scored on typing feel, build quality, programmability, and developer-specific features.",
      buyingAdvice: "When shopping for a programming keyboard, prioritize typing feel and build quality — you will use this for hours daily. Hot-swappable switches let you experiment without committing. Our top picks balance real-world user satisfaction with developer ergonomics.",
      top10: [
        {
          rank: 1,
          product: { brand: "Keychron", model: "Q1 Pro", slug: "keychron-q1-pro", category: "Mechanical Keyboard" },
          summary: "The default recommendation on r/MechanicalKeyboards. Gasket mount, hot-swappable, and wireless — ticks every box.",
          tagline: "The default recommendation on r/MechanicalKeyboards.",
          rankLabel: "Our Pick",
          pros: ["Gasket mount", "Hot-swappable", "Wireless"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["gasket mount", "hot-swappable", "wireless"],
          redditEvidence: [
            { quote: "Q1 Pro is the keyboard I recommend to every programmer who asks. It's the complete package.", url: "https://reddit.com/r/MechanicalKeyboards/example1" },
            { quote: "Typing on this thing all day is a joy. The gasket mount makes a huge difference.", url: "https://reddit.com/r/programming/example1" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "medium", Trustpilot: "low", Web: "high" },
          sourceCount: 52,
          scores: { queryFit: 95, redditEndorsement: 93, socialProofCoverage: 80, riskScore: 8, confidenceScore: 92, overall: 93 },
          sources: [],
        },
        {
          rank: 2,
          product: { brand: "Leopold", model: "FC660M", slug: "leopold-fc660m", category: "Mechanical Keyboard" },
          summary: "No-frills, legendary build quality. The 'buy it for life' pick that programmers trust for years.",
          tagline: "No-frills, legendary build quality.",
          rankLabel: "Runner-Up",
          pros: ["Exceptional build", "PBT keycaps", "Compact 65%"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["exceptional build", "PBT keycaps", "compact 65%"],
          redditEvidence: [
            { quote: "My Leopold has been my daily driver for 5 years. Still feels brand new.", url: "https://reddit.com/r/MechanicalKeyboards/example2" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "none", Trustpilot: "low", Web: "high" },
          sourceCount: 38,
          scores: { queryFit: 88, redditEndorsement: 90, socialProofCoverage: 65, riskScore: 5, confidenceScore: 88, overall: 88 },
          sources: [],
        },
        {
          rank: 3,
          product: { brand: "HHKB", model: "Professional Hybrid Type-S", slug: "hhkb-professional-hybrid", category: "Mechanical Keyboard" },
          summary: "Topre switches and a layout designed by programmers for programmers. Cult following in the dev community.",
          tagline: "Topre switches and a layout designed by programmers for programmers.",
          rankLabel: "Also Great",
          pros: ["Topre switches", "Programmer layout", "Compact"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["Topre switches", "programmer layout", "compact"],
          redditEvidence: [
            { quote: "Once you go HHKB you never go back. The layout is perfect for Vim and terminal work.", url: "https://reddit.com/r/MechanicalKeyboards/example3" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "low", Trustpilot: "none", Web: "high" },
          sourceCount: 34,
          scores: { queryFit: 90, redditEndorsement: 88, socialProofCoverage: 58, riskScore: 10, confidenceScore: 85, overall: 86 },
          sources: [],
        },
        {
          rank: 4,
          product: { brand: "ZSA", model: "Voyager", slug: "zsa-voyager", category: "Split Keyboard" },
          summary: "Ultra-thin split keyboard with a powerful configurator. Ideal for ergonomic-minded developers.",
          tagline: "Ultra-thin split keyboard with a powerful configurator.",
          rankLabel: undefined,
          pros: ["Split ergonomic", "Low profile", "Oryx configurator"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["split ergonomic", "low profile", "Oryx configurator"],
          redditEvidence: [
            { quote: "The Voyager + Oryx combo is incredible for setting up layers for coding shortcuts.", url: "https://reddit.com/r/ErgoMechKeyboards/example4" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "low", Trustpilot: "medium", Web: "high" },
          sourceCount: 29,
          scores: { queryFit: 88, redditEndorsement: 82, socialProofCoverage: 70, riskScore: 15, confidenceScore: 80, overall: 82 },
          sources: [],
        },
        {
          rank: 5,
          product: { brand: "Kinesis", model: "Advantage360 Pro", slug: "kinesis-advantage360-pro", category: "Split Keyboard" },
          summary: "Contoured split layout with decades of ergonomic research behind it. Steep learning curve but devotees are vocal.",
          tagline: "Contoured split layout with decades of ergonomic research behind it.",
          rankLabel: undefined,
          pros: ["Contoured wells", "Split design", "ZMK firmware"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["contoured wells", "split design", "ZMK firmware"],
          redditEvidence: [
            { quote: "Took me 2 weeks to adjust but I'll never go back. My wrist pain is completely gone.", url: "https://reddit.com/r/ErgoMechKeyboards/example5" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "high", TikTok: "none", Trustpilot: "low", Web: "medium" },
          sourceCount: 24,
          scores: { queryFit: 80, redditEndorsement: 78, socialProofCoverage: 55, riskScore: 20, confidenceScore: 72, overall: 74 },
          sources: [],
        },
        {
          rank: 6,
          product: { brand: "Keychron", model: "K2 Pro", slug: "keychron-k2-pro", category: "Mechanical Keyboard" },
          summary: "More affordable Keychron option with a 75% layout. Best entry point into quality mechanical keyboards.",
          tagline: "More affordable Keychron option with a 75% layout.",
          rankLabel: undefined,
          pros: ["75% layout", "Affordable", "Mac compatible"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["75% layout", "affordable", "Mac compatible"],
          redditEvidence: [
            { quote: "K2 Pro is the best starter mech keyboard for developers. Mac layout out of the box is a plus.", url: "https://reddit.com/r/MechanicalKeyboards/example6" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "medium", Trustpilot: "low", Web: "high" },
          sourceCount: 30,
          scores: { queryFit: 85, redditEndorsement: 75, socialProofCoverage: 72, riskScore: 10, confidenceScore: 78, overall: 78 },
          sources: [],
        },
        {
          rank: 7,
          product: { brand: "Ducky", model: "One 3 SF", slug: "ducky-one-3-sf", category: "Mechanical Keyboard" },
          summary: "65% with hot-swap and great stock keycaps. Solid reputation in the gaming and dev communities.",
          tagline: "65% with hot-swap and great stock keycaps.",
          rankLabel: undefined,
          pros: ["65% compact", "Hot-swappable", "PBT keycaps"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["65% compact", "hot-swappable", "PBT keycaps"],
          redditEvidence: [
            { quote: "Ducky One 3 is the safe pick. Great out of box and even better with custom switches.", url: "https://reddit.com/r/MechanicalKeyboards/example7" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "medium", Trustpilot: "low", Web: "high" },
          sourceCount: 22,
          scores: { queryFit: 78, redditEndorsement: 70, socialProofCoverage: 65, riskScore: 12, confidenceScore: 70, overall: 72 },
          sources: [],
        },
        {
          rank: 8,
          product: { brand: "NuPhy", model: "Air75 V2", slug: "nuphy-air75-v2", category: "Mechanical Keyboard" },
          summary: "Low-profile mechanical with a laptop-like form factor. Great for devs who switch between laptop and desktop.",
          tagline: "Low-profile mechanical with a laptop-like form factor.",
          rankLabel: undefined,
          pros: ["Low profile", "75% layout", "Multi-device"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["low profile", "75% layout", "multi-device"],
          redditEvidence: [
            { quote: "The Air75 bridges the gap between laptop feel and mechanical satisfaction perfectly.", url: "https://reddit.com/r/MechanicalKeyboards/example8" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "high", Trustpilot: "low", Web: "medium" },
          sourceCount: 20,
          scores: { queryFit: 75, redditEndorsement: 65, socialProofCoverage: 68, riskScore: 15, confidenceScore: 65, overall: 68 },
          sources: [],
        },
        {
          rank: 9,
          product: { brand: "Realforce", model: "R3", slug: "realforce-r3", category: "Mechanical Keyboard" },
          summary: "Premium Topre with variable weighting. Loved by Japanese devs and typing purists.",
          tagline: "Premium Topre with variable weighting.",
          rankLabel: undefined,
          pros: ["Topre switches", "Variable weighting", "Premium feel"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["Topre switches", "variable weighting", "premium feel"],
          redditEvidence: [
            { quote: "Realforce variable weighting is amazing for long coding sessions. Pinkies thank you.", url: "https://reddit.com/r/MechanicalKeyboards/example9" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "none", Trustpilot: "none", Web: "medium" },
          sourceCount: 15,
          scores: { queryFit: 80, redditEndorsement: 62, socialProofCoverage: 40, riskScore: 10, confidenceScore: 58, overall: 62 },
          sources: [],
        },
        {
          rank: 10,
          product: { brand: "Logitech", model: "MX Mechanical", slug: "logitech-mx-mechanical", category: "Mechanical Keyboard" },
          summary: "For devs who want mechanical feel within the Logitech ecosystem. Easy multi-device switching.",
          tagline: "For devs who want mechanical feel within the Logitech ecosystem.",
          rankLabel: undefined,
          pros: ["Multi-device", "Logi Options+", "Low profile mechanical"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["multi-device", "Logi Options+", "low profile mechanical"],
          redditEvidence: [
            { quote: "If you're already in the Logi ecosystem it's the easiest choice. Switches between Mac and PC seamlessly.", url: "https://reddit.com/r/LogitechG/example10" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "medium", Trustpilot: "medium", Web: "high" },
          sourceCount: 24,
          scores: { queryFit: 70, redditEndorsement: 55, socialProofCoverage: 75, riskScore: 12, confidenceScore: 60, overall: 62 },
          sources: [],
        },
      ],
    },
  },
  {
    slug: "running-shoes-for-flat-feet",
    query: "running shoes for flat feet",
    data: {
      rawQuery: "running shoes for flat feet",
      parsedIntent: {
        useCase: "running with flat feet / overpronation",
        constraints: ["arch support", "stability features"],
        mustHaves: ["motion control or stability", "good cushioning"],
        niceToHaves: ["lightweight", "breathable"],
      },
      candidateCount: 96,
      methodology: "We analyzed 96+ running shoes by gathering real user opinions from Reddit, TikTok, Trustpilot, and review sites. Products were scored on arch support, pronation control, cushioning, and comfort for flat-footed runners.",
      buyingAdvice: "When shopping for running shoes for flat feet, prioritize stability features and proper arch support. Visit a specialty running store for a gait analysis if possible. Our top picks balance real-world user satisfaction with podiatrist-recommended design.",
      top10: [
        {
          rank: 1,
          product: { brand: "Brooks", model: "Adrenaline GTS 24", slug: "brooks-adrenaline-gts-24", category: "Stability Running Shoe" },
          summary: "The go-to stability shoe recommended by podiatrists and runners alike. GuideRails support system prevents overpronation without feeling restrictive.",
          tagline: "The go-to stability shoe recommended by podiatrists and runners alike.",
          rankLabel: "Our Pick",
          pros: ["GuideRails support", "Plush cushion", "Podiatrist recommended"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["GuideRails support", "plush cushion", "podiatrist recommended"],
          redditEvidence: [
            { quote: "My podiatrist recommended these and they completely eliminated my shin splints from flat feet.", url: "https://reddit.com/r/running/example1" },
            { quote: "Adrenaline GTS is the gold standard for flat-footed runners. On my 4th pair.", url: "https://reddit.com/r/RunningShoeGeeks/example1" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "medium", Trustpilot: "medium", Web: "high" },
          sourceCount: 45,
          scores: { queryFit: 96, redditEndorsement: 92, socialProofCoverage: 85, riskScore: 5, confidenceScore: 94, overall: 94 },
          sources: [],
        },
        {
          rank: 2,
          product: { brand: "ASICS", model: "Gel-Kayano 31", slug: "asics-gel-kayano-31", category: "Stability Running Shoe" },
          summary: "Legendary stability shoe with FF Blast+ cushioning. Consistently top-ranked for overpronation control.",
          tagline: "Legendary stability shoe with FF Blast+ cushioning.",
          rankLabel: "Runner-Up",
          pros: ["4D guidance system", "FF Blast+", "Structured support"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["4D guidance system", "FF Blast+", "structured support"],
          redditEvidence: [
            { quote: "Kayano has been my go-to for 10+ years of running with flat feet. Never lets me down.", url: "https://reddit.com/r/running/example2" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "medium", Trustpilot: "high", Web: "high" },
          sourceCount: 42,
          scores: { queryFit: 94, redditEndorsement: 88, socialProofCoverage: 88, riskScore: 5, confidenceScore: 92, overall: 92 },
          sources: [],
        },
        {
          rank: 3,
          product: { brand: "New Balance", model: "860v14", slug: "new-balance-860v14", category: "Stability Running Shoe" },
          summary: "Medial post for pronation control with FreshFoam X cushioning. A reliable all-rounder.",
          tagline: "Medial post for pronation control with FreshFoam X cushioning.",
          rankLabel: "Also Great",
          pros: ["Medial post", "FreshFoam X", "Wide widths available"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["medial post", "FreshFoam X", "wide widths available"],
          redditEvidence: [
            { quote: "NB 860 in wide is a game changer for my flat, wide feet. Best fit I've ever had.", url: "https://reddit.com/r/RunningShoeGeeks/example3" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "low", Trustpilot: "medium", Web: "high" },
          sourceCount: 35,
          scores: { queryFit: 90, redditEndorsement: 82, socialProofCoverage: 75, riskScore: 8, confidenceScore: 85, overall: 86 },
          sources: [],
        },
        {
          rank: 4,
          product: { brand: "Saucony", model: "Guide 17", slug: "saucony-guide-17", category: "Stability Running Shoe" },
          summary: "Lightweight stability with PWRRUN+ foam. Great for runners who want support without the bulk.",
          tagline: "Lightweight stability with PWRRUN+ foam.",
          rankLabel: undefined,
          pros: ["Lightweight stability", "PWRRUN+", "Responsive"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["lightweight stability", "PWRRUN+", "responsive"],
          redditEvidence: [
            { quote: "Guide 17 is my favourite stability shoe. Feels fast but still supports my flat arches.", url: "https://reddit.com/r/running/example4" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "medium", TikTok: "low", Trustpilot: "medium", Web: "high" },
          sourceCount: 28,
          scores: { queryFit: 88, redditEndorsement: 78, socialProofCoverage: 70, riskScore: 10, confidenceScore: 80, overall: 82 },
          sources: [],
        },
        {
          rank: 5,
          product: { brand: "HOKA", model: "Arahi 7", slug: "hoka-arahi-7", category: "Stability Running Shoe" },
          summary: "HOKA's J-Frame stability in a max-cushion package. Ideal for flat-footed runners who want cloud-like comfort.",
          tagline: "HOKA's J-Frame stability in a max-cushion package.",
          rankLabel: undefined,
          pros: ["J-Frame support", "Max cushion", "Rocker geometry"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["J-Frame support", "max cushion", "rocker geometry"],
          redditEvidence: [
            { quote: "The Arahi is like running on clouds but my feet stay aligned. Perfect for my flat feet.", url: "https://reddit.com/r/RunningShoeGeeks/example5" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "medium", TikTok: "high", Trustpilot: "low", Web: "high" },
          sourceCount: 26,
          scores: { queryFit: 85, redditEndorsement: 75, socialProofCoverage: 72, riskScore: 12, confidenceScore: 78, overall: 80 },
          sources: [],
        },
        {
          rank: 6,
          product: { brand: "Mizuno", model: "Wave Inspire 20", slug: "mizuno-wave-inspire-20", category: "Stability Running Shoe" },
          summary: "Wave plate technology for a unique feel. Durable outsole and solid pronation control.",
          tagline: "Wave plate technology for a unique feel.",
          rankLabel: undefined,
          pros: ["Wave plate", "Durable outsole", "Pronation control"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["wave plate", "durable outsole", "pronation control"],
          redditEvidence: [
            { quote: "Mizuno doesn't get enough love. Wave Inspire is incredibly durable and supportive.", url: "https://reddit.com/r/running/example6" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "none", Trustpilot: "medium", Web: "medium" },
          sourceCount: 18,
          scores: { queryFit: 82, redditEndorsement: 65, socialProofCoverage: 58, riskScore: 10, confidenceScore: 68, overall: 70 },
          sources: [],
        },
        {
          rank: 7,
          product: { brand: "Brooks", model: "Beast GTS 24", slug: "brooks-beast-gts-24", category: "Motion Control Shoe" },
          summary: "Maximum support for severe overpronation. The heavy-duty option for flat-footed runners.",
          tagline: "Maximum support for severe overpronation.",
          rankLabel: undefined,
          pros: ["Max support", "Motion control", "Wide fit"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["max support", "motion control", "wide fit"],
          redditEvidence: [
            { quote: "If you have severely flat feet, skip stability shoes and go straight to Beast.", url: "https://reddit.com/r/running/example7" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "none", Trustpilot: "low", Web: "medium" },
          sourceCount: 16,
          scores: { queryFit: 85, redditEndorsement: 62, socialProofCoverage: 48, riskScore: 15, confidenceScore: 62, overall: 65 },
          sources: [],
        },
        {
          rank: 8,
          product: { brand: "Nike", model: "Structure 26", slug: "nike-structure-26", category: "Stability Running Shoe" },
          summary: "Nike's stability offering with a modern foam stack. Familiar Nike fit with pronation support.",
          tagline: "Nike's stability offering with a modern foam stack.",
          rankLabel: undefined,
          pros: ["React foam", "Crash rail", "Familiar Nike fit"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["React foam", "crash rail", "familiar Nike fit"],
          redditEvidence: [
            { quote: "Finally a Nike stability shoe that doesn't feel like a brick. Structure 26 is solid.", url: "https://reddit.com/r/RunningShoeGeeks/example8" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "medium", Trustpilot: "low", Web: "high" },
          sourceCount: 20,
          scores: { queryFit: 78, redditEndorsement: 60, socialProofCoverage: 68, riskScore: 15, confidenceScore: 62, overall: 65 },
          sources: [],
        },
        {
          rank: 9,
          product: { brand: "On", model: "Cloudflyer 4", slug: "on-cloudflyer-4", category: "Stability Running Shoe" },
          summary: "Swiss-engineered stability with Speedboard support. Trendy and functional.",
          tagline: "Swiss-engineered stability with Speedboard support.",
          rankLabel: undefined,
          pros: ["Speedboard", "CloudTec", "Modern design"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["Speedboard", "CloudTec", "modern design"],
          redditEvidence: [
            { quote: "Cloudflyer gives me the support I need without looking like an orthopedic shoe.", url: "https://reddit.com/r/running/example9" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "low", TikTok: "high", Trustpilot: "medium", Web: "medium" },
          sourceCount: 17,
          scores: { queryFit: 72, redditEndorsement: 50, socialProofCoverage: 65, riskScore: 20, confidenceScore: 55, overall: 58 },
          sources: [],
        },
        {
          rank: 10,
          product: { brand: "Altra", model: "Provision 8", slug: "altra-provision-8", category: "Stability Running Shoe" },
          summary: "Zero-drop with GuideRail. A unique pick for flat-footed runners who prefer a natural foot position.",
          tagline: "Zero-drop with GuideRail.",
          rankLabel: undefined,
          pros: ["Zero drop", "Foot-shaped toe box", "GuideRail"],
          cons: ["Limited social proof available", "May not suit all use cases"],
          fitCriteria: ["zero drop", "foot-shaped toe box", "GuideRail"],
          redditEvidence: [
            { quote: "Zero drop + stability seems contradictory but Altra makes it work for my flat feet.", url: "https://reddit.com/r/running/example10" },
          ],
          confidenceLevel: "low",
          platformCoverage: { Reddit: "low", TikTok: "low", Trustpilot: "none", Web: "medium" },
          sourceCount: 12,
          scores: { queryFit: 68, redditEndorsement: 45, socialProofCoverage: 42, riskScore: 25, confidenceScore: 42, overall: 48 },
          sources: [],
        },
      ],
    },
  },
  {
    slug: "noise-cancelling-earbuds-for-commuting",
    query: "noise cancelling earbuds for commuting",
    data: {
      rawQuery: "noise cancelling earbuds for commuting",
      parsedIntent: {
        useCase: "commuting on public transit",
        constraints: ["active noise cancellation"],
        mustHaves: ["strong ANC", "good battery life"],
        niceToHaves: ["transparency mode", "multipoint", "water resistance"],
      },
      candidateCount: 105,
      methodology: "We analyzed 105+ noise-cancelling earbuds by gathering real user opinions from Reddit, TikTok, Trustpilot, and review sites. Products were scored on ANC effectiveness, comfort for extended wear, sound quality, and battery life.",
      buyingAdvice: "When shopping for noise-cancelling earbuds for commuting, prioritize ANC strength and comfort for extended wear. Transparency mode is essential for safety awareness. Our top picks balance real-world user satisfaction with commuter-specific needs.",
      top10: [
        {
          rank: 1,
          product: { brand: "Sony", model: "WF-1000XM5", slug: "sony-wf-1000xm5", category: "True Wireless" },
          summary: "The undisputed ANC king. Best-in-class noise cancellation in a compact form factor that's perfect for daily commutes.",
          tagline: "The undisputed ANC king.",
          rankLabel: "Our Pick",
          pros: ["Class-leading ANC", "Compact", "LDAC support"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["class-leading ANC", "compact", "LDAC support"],
          redditEvidence: [
            { quote: "XM5s on the subway and I literally can't hear the train. It's almost unsettling how good the ANC is.", url: "https://reddit.com/r/headphones/example1" },
            { quote: "Daily commuter here. XM5 is the best purchase I've made for my sanity.", url: "https://reddit.com/r/earbuds/example1" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "high", Trustpilot: "medium", Web: "high" },
          sourceCount: 55,
          scores: { queryFit: 96, redditEndorsement: 94, socialProofCoverage: 92, riskScore: 5, confidenceScore: 95, overall: 95 },
          sources: [],
        },
        {
          rank: 2,
          product: { brand: "Apple", model: "AirPods Pro 2", slug: "airpods-pro-2", category: "True Wireless" },
          summary: "Best option for iPhone users. Excellent ANC with seamless Apple ecosystem integration and adaptive transparency.",
          tagline: "Best option for iPhone users.",
          rankLabel: "Runner-Up",
          pros: ["Apple ecosystem", "Adaptive transparency", "USB-C"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["Apple ecosystem", "adaptive transparency", "USB-C"],
          redditEvidence: [
            { quote: "If you have an iPhone, AirPods Pro 2 is a no-brainer for commuting. Transparency mode is magic.", url: "https://reddit.com/r/airpods/example2" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "high", Trustpilot: "medium", Web: "high" },
          sourceCount: 50,
          scores: { queryFit: 92, redditEndorsement: 90, socialProofCoverage: 95, riskScore: 5, confidenceScore: 93, overall: 93 },
          sources: [],
        },
        {
          rank: 3,
          product: { brand: "Bose", model: "QuietComfort Ultra Earbuds", slug: "bose-qc-ultra-earbuds", category: "True Wireless" },
          summary: "Bose's best ANC with immersive audio. Slightly larger but the noise cancellation rivals Sony.",
          tagline: "Bose's best ANC with immersive audio.",
          rankLabel: "Also Great",
          pros: ["Bose ANC", "Immersive audio", "CustomTune"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["Bose ANC", "immersive audio", "CustomTune"],
          redditEvidence: [
            { quote: "Bose QC Ultra are the comfiest earbuds I've worn for long commutes. ANC is top tier.", url: "https://reddit.com/r/bose/example3" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "medium", Trustpilot: "medium", Web: "high" },
          sourceCount: 40,
          scores: { queryFit: 92, redditEndorsement: 85, socialProofCoverage: 82, riskScore: 8, confidenceScore: 88, overall: 89 },
          sources: [],
        },
        {
          rank: 4,
          product: { brand: "Samsung", model: "Galaxy Buds3 Pro", slug: "samsung-galaxy-buds3-pro", category: "True Wireless" },
          summary: "Best for Samsung/Android users with strong ANC and a new blade design. Great multipoint support.",
          tagline: "Best for Samsung/Android users with strong ANC and a new blade design.",
          rankLabel: undefined,
          pros: ["Samsung ecosystem", "Blade design", "360 audio"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["Samsung ecosystem", "blade design", "360 audio"],
          redditEvidence: [
            { quote: "Galaxy Buds3 Pro ANC is a huge leap from previous gen. Finally competitive with Sony and Apple.", url: "https://reddit.com/r/galaxybuds/example4" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "medium", TikTok: "medium", Trustpilot: "low", Web: "high" },
          sourceCount: 30,
          scores: { queryFit: 85, redditEndorsement: 75, socialProofCoverage: 72, riskScore: 12, confidenceScore: 78, overall: 80 },
          sources: [],
        },
        {
          rank: 5,
          product: { brand: "Sennheiser", model: "Momentum True Wireless 4", slug: "sennheiser-mtw4", category: "True Wireless" },
          summary: "Audiophile-grade sound with excellent ANC. For commuters who care about sound quality as much as silence.",
          tagline: "Audiophile-grade sound with excellent ANC.",
          rankLabel: undefined,
          pros: ["Audiophile sound", "AptX Lossless", "Strong ANC"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["audiophile sound", "aptX Lossless", "strong ANC"],
          redditEvidence: [
            { quote: "If sound quality is your priority, Sennheiser MTW4 is unmatched. ANC is great too.", url: "https://reddit.com/r/headphones/example5" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "low", Trustpilot: "medium", Web: "high" },
          sourceCount: 28,
          scores: { queryFit: 85, redditEndorsement: 80, socialProofCoverage: 70, riskScore: 10, confidenceScore: 82, overall: 82 },
          sources: [],
        },
        {
          rank: 6,
          product: { brand: "Jabra", model: "Elite 10 Gen 2", slug: "jabra-elite-10-gen2", category: "True Wireless" },
          summary: "Excellent call quality and multipoint. Strong choice for commuters who take calls on the go.",
          tagline: "Excellent call quality and multipoint.",
          rankLabel: undefined,
          pros: ["Call quality", "Multipoint", "Dolby Atmos"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["call quality", "multipoint", "Dolby Atmos"],
          redditEvidence: [
            { quote: "Jabra Elite 10 is my pick for work commuters. Call quality is noticeably better than Sony/Apple.", url: "https://reddit.com/r/earbuds/example6" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "low", Trustpilot: "medium", Web: "high" },
          sourceCount: 22,
          scores: { queryFit: 82, redditEndorsement: 70, socialProofCoverage: 68, riskScore: 12, confidenceScore: 72, overall: 74 },
          sources: [],
        },
        {
          rank: 7,
          product: { brand: "Technics", model: "EAH-AZ80", slug: "technics-eah-az80", category: "True Wireless" },
          summary: "Premium Japanese engineering with 3-device multipoint. Under-the-radar gem with excellent ANC.",
          tagline: "Premium Japanese engineering with 3-device multipoint.",
          rankLabel: undefined,
          pros: ["3-device multipoint", "Premium build", "LDAC"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["3-device multipoint", "premium build", "LDAC"],
          redditEvidence: [
            { quote: "Technics AZ80 is the hidden gem in this space. Multipoint with 3 devices is a killer feature.", url: "https://reddit.com/r/headphones/example7" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "none", Trustpilot: "low", Web: "medium" },
          sourceCount: 18,
          scores: { queryFit: 80, redditEndorsement: 68, socialProofCoverage: 52, riskScore: 10, confidenceScore: 65, overall: 68 },
          sources: [],
        },
        {
          rank: 8,
          product: { brand: "Nothing", model: "Ear (2)", slug: "nothing-ear-2", category: "True Wireless" },
          summary: "Great value with surprisingly good ANC. The transparent design is a conversation starter on commutes.",
          tagline: "Great value with surprisingly good ANC.",
          rankLabel: undefined,
          pros: ["Great value", "Unique design", "Solid ANC"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["great value", "unique design", "solid ANC"],
          redditEvidence: [
            { quote: "Nothing Ear 2 punches way above its price. ANC handles subway noise well enough.", url: "https://reddit.com/r/NothingTech/example8" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "high", Trustpilot: "low", Web: "medium" },
          sourceCount: 20,
          scores: { queryFit: 75, redditEndorsement: 62, socialProofCoverage: 65, riskScore: 18, confidenceScore: 60, overall: 62 },
          sources: [],
        },
        {
          rank: 9,
          product: { brand: "Soundcore", model: "Liberty 4 NC", slug: "soundcore-liberty-4-nc", category: "True Wireless" },
          summary: "Budget ANC champion. Remarkable noise cancellation for under $80.",
          tagline: "Budget ANC champion.",
          rankLabel: undefined,
          pros: ["Budget ANC", "LDAC", "Long battery"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["budget ANC", "LDAC", "long battery"],
          redditEvidence: [
            { quote: "At $60-$80 the Liberty 4 NC offers 90% of what Sony does for a third of the price.", url: "https://reddit.com/r/headphones/example9" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "medium", Trustpilot: "none", Web: "medium" },
          sourceCount: 16,
          scores: { queryFit: 78, redditEndorsement: 58, socialProofCoverage: 55, riskScore: 20, confidenceScore: 55, overall: 58 },
          sources: [],
        },
        {
          rank: 10,
          product: { brand: "Google", model: "Pixel Buds Pro 2", slug: "google-pixel-buds-pro-2", category: "True Wireless" },
          summary: "Best for Pixel/Android users with Tensor chip-powered ANC. Compact and lightweight for all-day wear.",
          tagline: "Best for Pixel/Android users with Tensor chip-powered ANC.",
          rankLabel: undefined,
          pros: ["Tensor A1 chip", "Google integration", "Ultra compact"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["Tensor A1 chip", "Google integration", "ultra compact"],
          redditEvidence: [
            { quote: "Pixel Buds Pro 2 are tiny and the ANC is a big improvement. Perfect for Pixel users.", url: "https://reddit.com/r/GooglePixel/example10" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "low", Trustpilot: "none", Web: "high" },
          sourceCount: 15,
          scores: { queryFit: 75, redditEndorsement: 55, socialProofCoverage: 58, riskScore: 15, confidenceScore: 55, overall: 58 },
          sources: [],
        },
      ],
    },
  },
  {
    slug: "ergonomic-office-chair-for-back-pain",
    query: "ergonomic office chair for back pain",
    data: {
      rawQuery: "ergonomic office chair for back pain",
      parsedIntent: {
        useCase: "office work with back pain relief",
        constraints: ["ergonomic design", "lumbar support"],
        mustHaves: ["adjustable lumbar", "good back support"],
        niceToHaves: ["adjustable armrests", "headrest", "breathable mesh"],
      },
      candidateCount: 91,
      methodology: "We analyzed 91+ ergonomic office chairs by gathering real user opinions from Reddit, TikTok, Trustpilot, and review sites. Products were scored on lumbar support, adjustability, build quality, and long-term comfort for back pain relief.",
      buyingAdvice: "When shopping for an ergonomic chair for back pain, prioritize adjustable lumbar support and seat depth. Try before you buy if possible — used Herman Miller and Steelcase chairs offer incredible value. Our top picks balance real-world user satisfaction with clinical ergonomic design.",
      top10: [
        {
          rank: 1,
          product: { brand: "Herman Miller", model: "Aeron", slug: "herman-miller-aeron", category: "Ergonomic Chair" },
          summary: "The gold standard in ergonomic seating. PostureFit SL provides unmatched spinal support. Expensive but built to last 12+ years.",
          tagline: "The gold standard in ergonomic seating.",
          rankLabel: "Our Pick",
          pros: ["PostureFit SL", "8Z Pellicle mesh", "12-year warranty"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["PostureFit SL", "8Z Pellicle mesh", "12-year warranty"],
          redditEvidence: [
            { quote: "Bought a used Aeron 3 years ago and my chronic back pain has been manageable ever since.", url: "https://reddit.com/r/OfficeChairs/example1" },
            { quote: "The Aeron is expensive new but worth every penny. Buy it once, use it for a decade.", url: "https://reddit.com/r/BuyItForLife/example1" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "medium", Trustpilot: "medium", Web: "high" },
          sourceCount: 52,
          scores: { queryFit: 95, redditEndorsement: 94, socialProofCoverage: 88, riskScore: 5, confidenceScore: 95, overall: 95 },
          sources: [],
        },
        {
          rank: 2,
          product: { brand: "Steelcase", model: "Leap V2", slug: "steelcase-leap-v2", category: "Ergonomic Chair" },
          summary: "LiveBack technology flexes with your spine. Often preferred over the Aeron for lumbar support specifically.",
          tagline: "LiveBack technology flexes with your spine.",
          rankLabel: "Runner-Up",
          pros: ["LiveBack technology", "Adjustable lumbar", "Flexible back"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["LiveBack technology", "adjustable lumbar", "flexible back"],
          redditEvidence: [
            { quote: "Leap V2 literally fixed my lower back pain. The lumbar adjustment is the best in the business.", url: "https://reddit.com/r/OfficeChairs/example2" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "low", Trustpilot: "medium", Web: "high" },
          sourceCount: 44,
          scores: { queryFit: 95, redditEndorsement: 90, socialProofCoverage: 78, riskScore: 5, confidenceScore: 92, overall: 93 },
          sources: [],
        },
        {
          rank: 3,
          product: { brand: "Herman Miller", model: "Embody", slug: "herman-miller-embody", category: "Ergonomic Chair" },
          summary: "Designed with input from 30+ physicians. The pixelated support conforms to micro-movements of your back.",
          tagline: "Designed with input from 30+ physicians.",
          rankLabel: "Also Great",
          pros: ["Pixelated support", "Physician designed", "Backfit adjustment"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["pixelated support", "physician designed", "backfit adjustment"],
          redditEvidence: [
            { quote: "Embody is better than Aeron for back pain IMO. The back support is more dynamic.", url: "https://reddit.com/r/OfficeChairs/example3" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "medium", Trustpilot: "low", Web: "high" },
          sourceCount: 38,
          scores: { queryFit: 92, redditEndorsement: 85, socialProofCoverage: 72, riskScore: 8, confidenceScore: 88, overall: 88 },
          sources: [],
        },
        {
          rank: 4,
          product: { brand: "Steelcase", model: "Gesture", slug: "steelcase-gesture", category: "Ergonomic Chair" },
          summary: "Best armrest system in the industry with 360-degree arm support. Great for varied sitting positions.",
          tagline: "Best armrest system in the industry with 360-degree arm support.",
          rankLabel: undefined,
          pros: ["360 arms", "Flexible seat", "Wrap-back design"],
          cons: ["Premium pricing for some budgets"],
          fitCriteria: ["360 arms", "flexible seat", "wrap-back design"],
          redditEvidence: [
            { quote: "The Gesture arms are incredible. If you change positions a lot, this is the chair.", url: "https://reddit.com/r/OfficeChairs/example4" },
          ],
          confidenceLevel: "high",
          platformCoverage: { Reddit: "high", TikTok: "low", Trustpilot: "low", Web: "high" },
          sourceCount: 30,
          scores: { queryFit: 85, redditEndorsement: 80, socialProofCoverage: 65, riskScore: 8, confidenceScore: 82, overall: 82 },
          sources: [],
        },
        {
          rank: 5,
          product: { brand: "Haworth", model: "Fern", slug: "haworth-fern", category: "Ergonomic Chair" },
          summary: "Edge-to-edge back design eliminates pressure points. An underrated competitor to Herman Miller and Steelcase.",
          tagline: "Edge-to-edge back design eliminates pressure points.",
          rankLabel: undefined,
          pros: ["Edge-to-edge back", "Lumbar pads", "Organic design"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["edge-to-edge back", "lumbar pads", "organic design"],
          redditEvidence: [
            { quote: "Haworth Fern is the dark horse. Sat in it at a showroom and immediately preferred it over Aeron.", url: "https://reddit.com/r/OfficeChairs/example5" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "none", Trustpilot: "low", Web: "medium" },
          sourceCount: 20,
          scores: { queryFit: 82, redditEndorsement: 70, socialProofCoverage: 50, riskScore: 12, confidenceScore: 70, overall: 72 },
          sources: [],
        },
        {
          rank: 6,
          product: { brand: "Secretlab", model: "Titan Evo", slug: "secretlab-titan-evo", category: "Ergonomic Chair" },
          summary: "Gaming chair with genuine ergonomic features. Adjustable lumbar system is surprisingly effective for back pain.",
          tagline: "Gaming chair with genuine ergonomic features.",
          rankLabel: undefined,
          pros: ["Magnetic lumbar", "Cold-cure foam", "4-way armrests"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["magnetic lumbar", "cold-cure foam", "4-way armrests"],
          redditEvidence: [
            { quote: "I was skeptical of a 'gaming chair' but the Titan Evo lumbar support is legitimately good.", url: "https://reddit.com/r/OfficeChairs/example6" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "high", Trustpilot: "medium", Web: "high" },
          sourceCount: 28,
          scores: { queryFit: 75, redditEndorsement: 62, socialProofCoverage: 78, riskScore: 20, confidenceScore: 65, overall: 68 },
          sources: [],
        },
        {
          rank: 7,
          product: { brand: "Autonomous", model: "ErgoChair Pro", slug: "autonomous-ergochair-pro", category: "Ergonomic Chair" },
          summary: "Best value ergonomic chair with adjustable everything. Strong DTC following though mixed long-term reviews.",
          tagline: "Best value ergonomic chair with adjustable everything.",
          rankLabel: undefined,
          pros: ["Adjustable everything", "Mesh back", "Budget ergo"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["adjustable everything", "mesh back", "budget ergo"],
          redditEvidence: [
            { quote: "For under $500, ErgoChair Pro gives you 80% of a Steelcase at 30% of the price.", url: "https://reddit.com/r/homeoffice/example7" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "medium", Trustpilot: "low", Web: "medium" },
          sourceCount: 22,
          scores: { queryFit: 78, redditEndorsement: 55, socialProofCoverage: 60, riskScore: 25, confidenceScore: 58, overall: 60 },
          sources: [],
        },
        {
          rank: 8,
          product: { brand: "HON", model: "Ignition 2.0", slug: "hon-ignition-2", category: "Ergonomic Chair" },
          summary: "Budget workhorse with solid lumbar support. Popular in corporate offices and often found refurbished.",
          tagline: "Budget workhorse with solid lumbar support.",
          rankLabel: undefined,
          pros: ["Commercial grade", "Budget friendly", "Adjustable lumbar"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["commercial grade", "budget friendly", "adjustable lumbar"],
          redditEvidence: [
            { quote: "HON Ignition 2.0 is the best chair under $300 for actual back support. Don't sleep on it.", url: "https://reddit.com/r/OfficeChairs/example8" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "none", Trustpilot: "low", Web: "medium" },
          sourceCount: 16,
          scores: { queryFit: 75, redditEndorsement: 58, socialProofCoverage: 42, riskScore: 15, confidenceScore: 55, overall: 58 },
          sources: [],
        },
        {
          rank: 9,
          product: { brand: "Humanscale", model: "Freedom", slug: "humanscale-freedom", category: "Ergonomic Chair" },
          summary: "Self-adjusting recline mechanism — no knobs or levers. Designed to support your back automatically.",
          tagline: "Self-adjusting recline mechanism — no knobs or levers.",
          rankLabel: undefined,
          pros: ["Self-adjusting", "Minimalist", "Weight-sensitive recline"],
          cons: ["Some mixed reviews", "Not the top-rated option"],
          fitCriteria: ["self-adjusting", "minimalist", "weight-sensitive recline"],
          redditEvidence: [
            { quote: "Freedom chair adjusts to you instead of the other way around. Genius design for lazy ergo.", url: "https://reddit.com/r/OfficeChairs/example9" },
          ],
          confidenceLevel: "medium",
          platformCoverage: { Reddit: "medium", TikTok: "none", Trustpilot: "medium", Web: "medium" },
          sourceCount: 15,
          scores: { queryFit: 80, redditEndorsement: 60, socialProofCoverage: 50, riskScore: 12, confidenceScore: 58, overall: 62 },
          sources: [],
        },
        {
          rank: 10,
          product: { brand: "Sihoo", model: "Doro-C300", slug: "sihoo-doro-c300", category: "Ergonomic Chair" },
          summary: "Budget mesh chair with self-adaptive lumbar. The viral TikTok/Amazon pick with solid reviews for the price.",
          tagline: "Budget mesh chair with self-adaptive lumbar.",
          rankLabel: undefined,
          pros: ["Self-adaptive lumbar", "Mesh back", "Budget"],
          cons: ["Limited social proof available", "May not suit all use cases"],
          fitCriteria: ["self-adaptive lumbar", "mesh back", "budget"],
          redditEvidence: [
            { quote: "Sihoo Doro-C300 is the best budget ergo chair I've tried. Self-adjusting lumbar actually works.", url: "https://reddit.com/r/OfficeChairs/example10" },
          ],
          confidenceLevel: "low",
          platformCoverage: { Reddit: "low", TikTok: "high", Trustpilot: "none", Web: "medium" },
          sourceCount: 14,
          scores: { queryFit: 72, redditEndorsement: 45, socialProofCoverage: 55, riskScore: 30, confidenceScore: 42, overall: 48 },
          sources: [],
        },
      ],
    },
  },
];

/** Look up a featured search by slug */
export function getFeaturedSearch(slug: string): FeaturedSearch | undefined {
  return featuredSearches.find((fs) => fs.slug === slug);
}

/** Get all featured searches (for static generation and homepage) */
export function getAllFeaturedSlugs(): string[] {
  return featuredSearches.map((fs) => fs.slug);
}
